apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-agent
  labels:
    name: chaos-agent
spec:
  selector:
    matchLabels:
      name: chaos-agent
  template:
    metadata:
      labels:
        name: chaos-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
        - name: chaos-agent
          image: {{ .Values.images.chaosagnet.repository }}:{{ .Values.images.chaosagnet.version }}
          imagePullPolicy: "{{ .Values.images.chaosagnet.pullPolicy }}"
          env:
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            {{- if .Values.controller.transport_endpoint }}
            - '--transport.endpoint={{ .Values.controller.transport_endpoint }}'
            {{- end }}
            {{- if .Values.env.mode }}
            - '--agent.mode={{ .Values.env.mode }}'
            {{- end }}
            {{- if .Values.env.name }}
            - '--namespace={{ .Values.env.name }}'
            {{- end }}
            {{- if .Values.env.debug }}
            - '--debug'
            {{- end }}
            {{- if .Values.log.output }}
            - '--log.output={{ .Values.log.output }}'
            {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /etc/hosts
              name: hosts

      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker-socket
        - hostPath:
            path: /etc/hosts
          name: hosts
      serviceAccountName: chaos-agent
